/**
 * Every user-facing string lives here so Tamil can be added later
 * (turn this into a per-locale map keyed by the same shape).
 */
export const copy = {
  brand: {
    name: "ShowMoto",
    tagline: "Your showroom. One smart link.",
    // Shown on the public privacy policy and terms pages. Replace with a support mailbox on your domain.
    contactEmail: "manibalan.fameix@gmail.com",
  },
  marketing: {
    heading: "Sell used cars from one link",
    body: "Add a car in under two minutes. Share one link on Instagram and WhatsApp. Get test drive leads under your own name.",
    cta: "Dealer sign in",
  },
  tenant: {
    poweredBy: "Powered by",
    cars: (n: number) => (n === 1 ? "1 car available" : `${n} cars available`),
    noCars: "No cars listed right now. Please check back soon.",
    searchResults: (n: number, q: string) => (n === 1 ? `1 car matches "${q}"` : `${n} cars match "${q}"`),
    noSearchResults: "No cars match your search.",
    emptyHint: "Ask the dealer about upcoming stock.",
    priceOnRequest: "Price on request",
    car: {
      verified: "Verified from RTO records",
      owners: (n: number) => (n === 1 ? "1st owner" : n === 2 ? "2nd owner" : n === 3 ? "3rd owner" : `${n}th owner`),
      sold: "This car has been sold",
      onHold: "This car is on hold",
      previewNote: "Full details, EMI estimate and test drive booking are coming soon.",
      contact: "Call dealer",
      prevPhoto: "Previous photo",
      nextPhoto: "Next photo",
      emiFrom: (emi: string) => `EMI ₹${emi}/m*`,
      reasonsToBuy: (first: string, moreCount: number) => (moreCount > 0 ? `${first} & ${moreCount} more reason${moreCount === 1 ? "" : "s"} to buy` : first),
    },
    call: "Call dealer",
    km: "km",
    kmDriven: (km: string) => `${km} km driven`,
    chat: {
      openLabel: "Chat with us",
      title: "Chat",
      generalGreeting: (name: string) => `Hi! Ask me anything about ${name}'s cars — I'm happy to help you find the right one.`,
      carGreeting: "Hi! Ask me anything about this car.",
      placeholder: "Type a message…",
      send: "Send",
      close: "Close chat",
      thinking: "Typing…",
      error: "Something went wrong. Please try again.",
      rateLimited: "Too many messages just now. Please wait a moment and try again.",
      unavailable: "Chat isn't available right now.",
      generalQuestions: [
        "What cars do you have in stock?",
        "Do you have any automatic cars?",
        "What documents do I need to buy a car?",
        "How do I book a test drive?",
      ],
      carQuestions: [
        "Is this car accident-free?",
        "What is the on-road price?",
        "Can I get a loan for this car?",
        "What is the condition of the tyres and battery?",
      ],
    },
    filters: {
      title: "Filters",
      clearAll: "Clear all",
      model: "Model",
      fuel: "Fuel type",
      transmission: "Transmission",
      price: "Price range",
      sort: "Sort",
      inventory: "Inventory",
      showResults: (n: number) => (n === 1 ? "Show 1 car" : `Show ${n} cars`),
      openFilters: "Filters",
    },
  },
  auth: {
    signInTitle: "Dealer sign in",
    signInBody: "Sign in to manage your cars and leads.",
    signInGoogle: "Continue with Google",
    signOut: "Sign out",
    devBypass: "Development mode: you can use email/password or open the demo dealer.",
    notConfigured: "Sign-in is not configured yet. Add the Firebase keys to the environment.",
  },
  admin: {
    nav: {
      platform: "Platform",
      dashboard: "Dashboard",
      cars: "Cars",
      addCar: "Add a car",
      soldCars: "Sold cars",
      leads: "Leads",
      pipeline: "Pipeline",
      transfers: "RC transfers",
      reports: "Reports",
      settings: "Settings",
      hours: "Business hours",
      theme: "Theme",
      team: "Team",
      recentCars: "Recent cars",
      viewCar: "View car",
      shareCar: "Share on WhatsApp",
      archiveCar: "Archive car",
      more: "More",
      more_sr: "More options",
      toggle: "Toggle",
      viewPage: "View my page",
      help: "Help",
      adminCrumb: "Dealer admin",
      upgrade: "Upgrade plan",
      account: "Account",
      billing: "Billing",
      notifications: "Notifications",
      shareText: (url: string) => `Take a look at this car: ${url}`,
    },
    cars: {
      title: "Cars",
      add: "Add a car",
      continueDraft: "Continue",
      empty: { title: "No cars yet", body: "Add your first car in about two minutes. All you need is a phone and the car." },
      status: { draft: "Draft", live: "Live", on_hold: "On hold", sold: "Sold", archived: "Archived" },
      untitled: "New car",
      priceOnRequest: "No price yet",
      manage: {
        share: "Share this car",
        editPhotos: "Edit photos",
        openPage: "Open public page",
        facts: "Details",
        reg: "Registration",
        owners: "Owners",
        insurance: "Insurance valid till",
        loan: "Loan (hypothecation)",
        loanCleared: "Cleared",
        loanActive: "Active",
        unknown: "Not known",
        verified: "Verified from RTO records",
        unverified: "Not verified against RTO records",
        km: "km driven",
        price: "Asking price",
      },
    },
    addCar: {
      title: "Add a car",
      steps: { plate: "Plate", car: "Car", photos: "Photos", marketplace: "Details", price: "Price" },
      back: "Back",
      next: "Continue",
      exit: "Exit",
      start: {
        title: "Add a car",
        subtitle: "Start a new listing or pick up a draft.",
        newTitle: "Add a new car",
        newBody: "Start with the number plate and we fill in the rest.",
        continueTitle: "Continue with an existing draft",
        continueBody: "Resume a car you started earlier.",
      },
      carSubtitle: "Check the RTO details and pick the exact variant.",
      plate: {
        title: "Start with the number plate",
        body: "Take a clear photo of the plate and we read the number for you.",
        take: "Take plate photo",
        retake: "Retake photo",
        reading: "Reading the plate…",
        label: "Registration number",
        placeholder: "TN 11 AB 1234",
        checkNumber: "Check the number and fix it if needed.",
        typeNumber: "Type the number, for example TN 11 AB 1234.",
        notRead: "We could not read the plate. Please type the number.",
        noAi: "Plate reading is not set up yet. Please type the number.",
        invalid: "That does not look like an Indian registration number.",
        start: "Look up this car",
        starting: "Checking RTO records…",
        rateLimited: "Too many lookups just now. Please wait a few minutes.",
        failed: "Something went wrong. Please try again.",
      },
      details: {
        title: "Confirm the car",
        rcTitle: "From RTO records",
        rcUnverified: "Demo data. Not from real RTO records.",
        rcMissing: "We could not fetch RTO details. You can fill them in.",
        rcNotFound: "No RC found for this number. Check the number, or fill in the details.",
        retryRc: "Try again",
        year: "Year",
        owners: "Owners",
        colour: "Colour",
        fuel: "Fuel",
        insurance: "Insurance valid till",
        loan: "Loan",
        loanCleared: "No loan on record",
        loanActive: "Loan on record",
        findTitle: "Which car is it?",
        findHint: "Type what you would say: year, model, variant. For example: 2017 baleno alpha diesel.",
        findPlaceholder: "2017 baleno alpha diesel",
        find: "Find my car",
        finding: "Finding…",
        pick: "Tap the right one",
        noMatch: "No match yet. Try the model name and variant, like: creta sx diesel.",
        matchAi: "Best match",
        saveFacts: "Save details",
        selected: "Selected",
      },
      photos: {
        title: "Photos",
        body: "12 photos, guided one by one. The first photo is the cover, so start there.",
        start: "Start guided capture",
        continueCapture: "Continue capture",
        retake: "Retake",
        take: "Take photo",
        uploaded: (n: number, total: number) => `${n} of ${total} uploaded`,
        waiting: "Waiting for signal. Uploads continue on their own.",
        failed: "Some uploads failed",
        retry: "Retry",
        cover: "Cover",
        video: {
          title: "Walkaround video (optional)",
          body: "A slow walk around the car. We check which angles it shows. Video never replaces your photos.",
          add: "Add video",
          replace: "Replace video",
          processing: "Processing video…",
          ready: "Video ready",
          covers: (n: number, total: number) => `The video shows ${n} of ${total} angles.`,
          notShown: "Not in the video:",
          photosNeeded: "Photos still needed for:",
          allPhotos: "You have a photo for every angle.",
        },
      },
      marketplace: {
        title: "Marketplace details",
        body: "Add the buyer-facing information shown on a full marketplace car page.",
        overview: "Car overview",
        pricing: "EMI and booking",
        trust: "Inspection and trust",
        condition: "Condition",
        specs: "Specifications",
        features: "Features",
        protection: "Protection plans",
        save: "Save details",
        saving: "Saving...",
        saved: "Saved",
        failed: "Could not save details. Please try again.",
        optional: "Optional, but useful for buyers.",
      },
      camera: {
        counter: (i: number, total: number) => `${i} of ${total}`,
        skip: "Skip",
        close: "Done",
        gallery: "Choose photo",
        shutter: "Take photo",
        starting: "Starting camera…",
        fallback: "Camera not available here. Take or choose a photo instead.",
        takeOrChoose: "Take or choose photo",
        saved: "Saved",
      },
      price: {
        title: "Price and kilometres",
        body: "Just two numbers, then it is live.",
        priceLabel: "Asking price (₹)",
        kmLabel: "Kilometres driven",
        publish: "Publish",
        publishing: "Publishing…",
        needVariant: "Pick the car model first.",
        needYear: "Add the year of the car.",
        needHero: "Take the cover photo (Front ¾) first.",
        heroUploading: "Cover photo is still uploading. Publishing unlocks as soon as it lands.",
        badPrice: "Enter a price between ₹10,000 and ₹5,00,00,000.",
        badKm: "Enter the kilometres driven.",
        capReached: "You have reached the live-car limit for your plan.",
        failed: "Could not publish. Please try again.",
        closed: "This car is sold or archived.",
      },
      done: {
        title: "Your car is live",
        body: "Share the link and the photos. Buyers see your brand, not ours.",
        link: "Share link",
        caption: "Instagram caption",
        copy: "Copy",
        copied: "Copied",
        share: "Share photos and caption",
        download: "Download photos",
        carousel: "Carousel photos (4:5)",
        preparing: "Preparing photos…",
        open: "Open public page",
        another: "Add another car",
        allCars: "Back to cars",
        pageSoon: "The public page is a basic preview for now.",
        shareText: "Take a look at this car",
      },
    },
    angles: {
      front_three_quarter: { label: "Front ¾", hint: "Stand at a front corner, a few steps back. Get the whole car in the frame." },
      rear_three_quarter: { label: "Rear ¾", hint: "Go to the opposite rear corner. Whole car in the frame." },
      side_left: { label: "Left side", hint: "Stand square to the left side. Keep all four wheels in view." },
      side_right: { label: "Right side", hint: "Stand square to the right side. Keep all four wheels in view." },
      dashboard: { label: "Dashboard", hint: "Sit in the driver seat. Show the steering wheel and the whole dashboard." },
      odometer: { label: "Odometer", hint: "Ignition on. Move close so the kilometre reading is sharp." },
      front_seats: { label: "Front seats", hint: "Open a front door. Show both front seats." },
      rear_seats: { label: "Rear seats", hint: "Open a rear door. Show the full back seat." },
      boot: { label: "Boot", hint: "Open the boot. Show the floor and the spare wheel area." },
      engine_bay: { label: "Engine bay", hint: "Open the bonnet. Show the whole engine bay from above." },
      tyres_front: { label: "Front tyres", hint: "Get close to a front tyre. Show the tread and the wheel." },
      tyres_rear: { label: "Rear tyres", hint: "Get close to a rear tyre. Show the tread and the wheel." },
    },
    uploadPill: {
      uploading: (n: number) => `Uploading ${n} ${n === 1 ? "file" : "files"}…`,
      offline: "Offline. Uploads will continue when you are back online.",
      failed: (n: number) => `${n} ${n === 1 ? "upload" : "uploads"} failed`,
      retry: "Retry",
    },
    comingSoon: {
      title: "Coming soon",
      body: "This screen is on the way. It will appear here in an upcoming release.",
    },
    dashboard: {
      title: "Dashboard",
      welcome: (name: string) => `Welcome, ${name}`,
      liveCars: "Live cars",
      plan: "Plan",
      publicPage: "Your public page",
      openPage: "Open",
      noDealerTitle: "No dealership linked yet",
      noDealerBody:
        "Your Google account is not linked to a dealership. Setting up a new dealership arrives in the next release. Ask the owner to invite you as staff.",
      capUsage: (used: number, cap: number) => `${used} of ${cap}`,
    },
  },
} as const
